# Generated by Django 4.1.13 on 2026-09-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的家庭', max_length=64)),
                ('invite_code', models.CharField(max_length=16, unique=True)),
                ('owner_openid', models.CharField(db_index=True, max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, unique=True)),
                ('unionid', models.CharField(blank=True, default='', max_length=64)),
                ('nick_name', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='wxcloudrun.family')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_openid', models.CharField(db_index=True, max_length=64)),
                ('nick_name', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512)),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(blank=True, default='其他', max_length=32)),
                ('remark', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='wxcloudrun.family')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user_openid', 'date'], name='bills_user_op_53de81_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['family', 'date'], name='bills_family__bef082_idx'),
        ),
    ]
